development:
  adapter: postgresql
  encoding: unicode
  database: sweethome_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sweethome_test
  host: localhost

